#ifndef OPENGLGP_COMPONENTTYPEENUM_H
#define OPENGLGP_COMPONENTTYPEENUM_H

enum class ComponentType {
    CAMERA,
    PLAYERCNTROLLER,
    BLOCKMANAGER,
    INSTANCERENDERER
};

#endif //OPENGLGP_COMPONENTTYPEENUM_H
