#ifndef OPENGLGP_COMPONENTTYPEENUM_H
#define OPENGLGP_COMPONENTTYPEENUM_H

enum class ComponentType {
    CAMERA, //0
    PLAYERCNTROLLER, //1
    BLOCKMANAGER, //2
    INSTANCERENDERER, //3
    AUDIOSOURCE, //4
    MESHRENDERER, //5
    ENEMYAI, //6
    ANIMATION, //7
    CLOUDMANAGER, //8
    TURRET, //9
	PARTICLEGENERATOR //10
};

#endif //OPENGLGP_COMPONENTTYPEENUM_H
